import type { Metadata } from "next";
import "@/styles/reset.css"
import { LayoutComponent } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LayoutComponent>
          {children}
        </LayoutComponent>
      </body>
    </html>
  );
}
